### ISSUE TITLE
No Ligand Output in chai-1 Predictions

### ISSUE THREAD

**Issue by YangPH0624** [chaidiscovery/chai-lab#102]
I really appreciate the great work you’ve done with chai-1. However, I’m encountering an issue where the output doesn’t include any ligand information when predicting ligand-protein complexes. Could you please assist me in understanding this?

**Comment by YangPH0624** [comment]
for example：
protein（2）
VLRLVKDWNFTWSVVFLLITIVLQYGYPSRSMFVYVIKMFVLWLLWPASMALSIFCAVYPIDLASQIISGILAATSCAMWISYFVQSIRLFMRTGSWWSFNPESNCLLNVPIGGTTVVRPLVEDSTSVTAVVTDGYLKMAGMHFGACDFQRLPSEVTVAKPNVLIALKMIKRQAYGTNSGVAIYHRY
ligand（1）
CCO[C@H]1O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]([C@H]1C)[C@]42OO3

**Comment by liukuozy** [comment]
It seems that the FASTA headers for chai-1 need to follow a specific format. Could you try changing the FASTA headers to the following format?
For the protein: >protein|name=example-of-long-protein
For the ligand: >ligand|name=example-ligand-as-smiles

**Comment by wukevin** [comment]
It looks like this SMILES string is invalid (I checked a few online tools, and they all can't build a 2D structure from the string you posted). In the `chai-1` model itself, this results in that ligand chain failing during tokenization and being ignored for the remainder of folding. You can see this in the logged error messages when running the inference code locally on your input.

Can you share what molecule you're trying to model here and we can try to edit the smiles string to work?

**Comment by YangPH0624** [comment]
> It looks like this SMILES string is invalid (I checked a few online tools, and they all can't build a 2D structure from the string you posted). In the `chai-1` model itself, this results in that ligand chain failing during tokenization and being ignored for the remainder of folding. You can see this in the logged error messages when running the inference code locally on your input.
> 
> Can you share what molecule you're trying to model here and we can try to edit the smiles string to work?

And I check it using rdkit, which could recognized the smi. You could find it in zinc20(ZINC000100353857)

**Comment by YangPH0624** [comment]
![mel](https://github.com/user-attachments/assets/039157f5-f715-42ff-ac49-d2ca4e8d81d9)

**Comment by arogozhnikov** [comment]
zinc provides different smiles:

```
CCO[C@H]1O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]([C@H]1C)[C@]42OO3 # correct 
CCO[C@H]1O[C@@h]2O[C@]3(C)CC[C@H]4C@HCCC@@H[C@]42OO3   # in your input
```

when provided with smiles from zinc dataset, prediction contains the ligand

**Comment by YangPH0624** [comment]
> zinc provides different smiles:
> 
> ```
> CCO[C@H]1O[C@@H]2O[C@]3(C)CC[C@H]4[C@H](C)CC[C@@H]([C@H]1C)[C@]42OO3 # correct 
> CCO[C@H]1O[C@@h]2O[C@]3(C)CC[C@H]4C@HCCC@@H[C@]42OO3   # in your input
> ```
> 
> when provided with smiles from zinc dataset, prediction contains the ligand

i am sorry for my mistakes, thank u..
