### ISSUE TITLE
Token length extension

### ISSUE THREAD

**Issue by JustABiologist** [chaidiscovery/chai-lab#118]
Hi dear Team, 
First of all thanks for this amazing resource! This is super cool and helpful in many ways! 
I am working with a protein complex that only is marginally longer than 2048AA -> 2400AA and have access to H100/A100 80GB GPUS so I think I would be able to run it. I already read #77 -> Cubic scaling, I know.

So I skimmed the code a little. There is only a checking function I saw so far, if I disable that will the model run or did you guys hardcode anything more that would make this unfeasible? If not I would just fork the repo and run my version with longer context :)

Love your work and again thanks so much!

**Comment by arogozhnikov** [comment]
Thanks for kind words, 

> if I disable that will the model run or did you guys hardcode anything more that would make this unfeasible?

There is no _our_ hard-coded constraint, but AFAICT models won't work for size that is _different_ from what was exported, and largest exported was 2048 (previously I tried and it didn't work).

**Comment by JustABiologist** [comment]
Okay thank you I will give it a shot and report back!

**Comment by JustABiologist** [comment]
Hey gave it a shot. Guess the diffusion size is fixed. At least it did not work for me and makes sense that it would not work.
