### ISSUE TITLE
Is it possible to fine-tune the model

### ISSUE THREAD

**Issue by kehan777** [chaidiscovery/chai-lab#125]
**Appreciate your outstanding work!**

It appears that there is room for improvement in the prediction of antigen-antibody complexes. Is it feasible to make some fine-tuning adjustments? If so, could you provide guidance on how to proceed with these adjustments? Any methods or suggestions you could offer would be invaluable.

**Comment by joshim5** [comment]
The [License](https://github.com/chaidiscovery/chai-lab/blob/main/LICENSE.md) and [Acceptable Use Policy](https://www.chaidiscovery.com/acceptable-use-policy) prohibits fine-tuning of Chai-1.

If there is a specific usecase that you'd like to unlock, drop us a line at partnerships@chaidiscovery.com.

**Comment by kehan777** [comment]
I see. Thank you
