### ISSUE TITLE
Update torch export files

### ISSUE THREAD

**Issue by maxall41** [chaidiscovery/chai-lab#132]
The model weight/definition files (`.pt2`) are out of date and can only be used with pytorch 2.3.1. Attempting to use the files with any other version (i.e: 2.5, 2.4, 2.3.0) results in the below error.

Pytorch 2.5 load error:
``` 
RuntimeError: Serialized version ['5', '1'] does not match our current schema version (7, 3).
```

There seems to be no way to upgrade an existing file to a newer schema version. Would it be possible to upload updated model files? It would also be great if  the .pt2 files could be compiled for AMD GPUs in addition to Nvidia GPUs (rel #33).

Motivation:

- Faster attention (https://pytorch.org/blog/pytorch2-5/, CuDNN backend for SDPA, up to 75% speed-up over FlashAttentionV2 on H100 or newer)
- GH200 Support (Technically you can use pytorch 2.3.1 on a GH200, but you have to compile it from source)
- Fixes issue with torch AMP (https://github.com/pytorch/pytorch/issues/124901)
- Theoretical support for AMD GPUs (Memory efficient attention on AMD GPUs was only implemented in >2.4.0. Requires compiled version.)
- Theoretical support for Intel GPUs (Only supported >2.4.0. Requires compiled version.)

**Comment by arogozhnikov** [comment]
thanks for reporting; we'll do smth about it.

**Comment by acs-at-lab** [comment]
support for pytorch2.5 would be greatly appreciated! Looking forward to it!

**Comment by conorfhayes** [comment]
Very much looking forward to support for torch 2.5 🎉🎉

**Comment by arogozhnikov** [comment]
This was fixed, should run normally on 2.5.1

Also, if anyone has AMD devices, I'd be curious if it works.

**Comment by conorfhayes** [comment]
While loading the models works for torch2.5.1, the predicted results are not good on AMD machines and do not match the server.

**Comment by arogozhnikov** [comment]
@conorfhayes do you have some nvidia devices to run test side-to-side? There unlikely to be complete parity because kernels are different; but figuring out which part of computations is different may be interesting
