### ISSUE TITLE
Output files from the v0.2.0 version

### ISSUE THREAD

**Issue by qhelleu** [chaidiscovery/chai-lab#140]
Hi,
Thanks a lot for the great work! 
I have tested the v0.2.0 and I tried to run the prediction on a bunch of protein sequences. In contrary to the v0.1.0 I only got the cif and npz files, and not the pdb and the json files. 
Is it the normal new behavior? In that case, what is the command to get the pdb files?

Thanks a lot,
Best.

**Comment by arogozhnikov** [comment]
Hi @qhelleu,

cif is the new pdb, see #49 for why, and npz now takes role of json.
