### ISSUE TITLE
Why there is a limit of 2048 tokens hardcoded in Chai-1?

### ISSUE THREAD

**Issue by lukasz-kozlowski** [chaidiscovery/chai-lab#152]
Initially, I thought the limit of 2048 tokens you have on the webserver was related to the machine/GPUs you are using at the backend, but it seems it is the same is also for the local installation:

I tried to run chai-1 for a longer sequence and I got:
**chai_lab.chai1.UnsupportedInputError: Too many tokens in input: 2789 > 2048. Please limit the length of the input sequence**

Is there any particular reason why you hardcoded to 2048? 

Initially, I guessed that maybe vRAM skyrocketing for longer sequences, and it is partly the case as for A100 40GB I was able to run chai for ~1000aa sequence (used initially 10GB, then 37GB for a short time, and most of the time during diffusion 27GB). Chai failed for 2048 on A100 40GB  (most likely the A100 80GB limit you set; the longest seq I could run on 40GB was 1550aa, 1625aa was already too much). Yet, today/tomorrow one can have better GPUs thus hardcoding this to 80GB aka 2048 tokens seems weird.

Additional question: maybe the model decays above 2048 (which is still reasonable as not so many such proteins in the training)?

**Comment by arogozhnikov** [comment]
Hi Lucasz,

> 1550aa, 1625aa was already too much

thresholds for exported model are  1024, 1536, 2048 (+ smaller ones), so if 1550 worked, 2048 is very likely to work too. Each size has its dedicated inference graph, which almost completely defines memory footprint for specific input size.

2048 fits well onto current hardware with a nice memory gap + covers most use-cases + we provide restraints, they can be used to handle smaller parts of complex.

> Additional question: maybe the model decays above 2048?

That's not what we observe. If you have some examples of (comparable) larger complexes that work worse, I'd be curious to look at such examples.

**Comment by lukasz-kozlowski** [comment]
1) On A100 40GB: 1000aa worked, 1500aa worked, 1550aa worked, 1625aa crashed, 1750aa crashed, 2048 crashed, 2789 crushed (maybe this depends also on sequence, but this is the outcome on a single sequence trimmed from C-terminus to meet the memory requirements)

2) going back to the main question: why to hardcode the 2048 limit? 

3) do you have any plot for the memory footprint?

**Comment by arogozhnikov** [comment]
> do you have any plot for the memory footprint?

I can't provide sufficient guarantees about memory allocations in torch to say "this is the memory allocation that you'll have", so I won't put those out (but you can if you want). I, for one, did not expect anything above 1536 to work on 40GB.

**Comment by lukasz-kozlowski** [comment]
the main question: why to hardcode the 2048 limit? 

ps. I want to test chai on H100 for longer seqs

**Comment by arogozhnikov** [comment]
requires engineering investment, and not a priority for now. See #77

**Comment by lukasz-kozlowski** [comment]
simply remove the hardcoding from the code and people will have a possibility to check it on the other GPUs even if you do not have such (this is as easy as commenting ~2 lines of code), in the worst scenario it will crush even on H100 for longer than 2048, but I guess that on H100 one will be able to run inference for 2500-3000aa
