### ISSUE TITLE
Inconsistent predictions

### ISSUE THREAD

**Issue by YidongSong** [chaidiscovery/chai-lab#174]
Why is the IPTM value for the structures predicted on the server 0.45, while the IPTM value for the structures predicted on the local machine is only 0.12, despite using the same input?

**Comment by wukevin** [comment]
> Why is the IPTM value for the structures predicted on the server 0.45, while the IPTM value for the structures predicted on the local machine is only 0.12, despite using the same input?

Are you using MSAs or single sequence modes consistently in this comparison?

**Comment by arogozhnikov** [comment]
sounds like double-post of #173, where @YidongSong got good results with A100, but not 3090, this has nothing to do with server/local
