### ISSUE TITLE
How to represent homomeric oligomers?

### ISSUE THREAD

**Issue by jiaweiguan** [chaidiscovery/chai-lab#18]
Hi, Chai team! I want to predict the structure of homomeric oligomers.
Can the following representation be used?
```
example_fasta = """
>protein|example-of-short-protein
AIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM
>protein|example-of-short-protein
AIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM
>protein|example-of-short-protein
AIQRTPKIQVYSRHPAENGKSNFLNCYVSGFHPSDIEVDLLKNGERIEKVEHSDLSFSKDWSFYLLYYTEFTPTEKDEYACRVNHVTLSQPKIVKWDRDM
""".strip()
```
But I found that in the output results, `token_asyms` is different from what I expected.

`token_asyms = tensor([1, 2, 3], device='cuda:0', dtype=torch.int32)`

**Comment by arogozhnikov** [comment]
Yes, that's correct input format. Here is one of PDBs that was generated by package with your inputs 

<img width="797" alt="Screenshot 2024-09-11 at 20 16 48" src="https://github.com/user-attachments/assets/aebf8e65-2848-472e-9c96-cbc370718a49">

**Comment by jiaweiguan** [comment]
I notice a phenomenon that different length ranges seem to correspond to different parameters, such as 256, 384, 512, 768。Why did you do this?

**Comment by arogozhnikov** [comment]
see #21, short answer: we want fast inference for different sizes, but facing limitations of graph export.

please don't put multiple different questions into the same issue - new users should be able to find answer by topic name.
