### ISSUE TITLE
License term

### ISSUE THREAD

**Issue by huhlim** [chaidiscovery/chai-lab#185]
I noticed that the license term has been updated to Apache 2.0, which allows its commercial usages. In contrast, [LICENSE.md](https://github.com/chaidiscovery/chai-lab/blob/main/LICENSE.md) still prohibits its commercial usages. I am wondering which one is the correct statement.

**Comment by joshim5** [comment]
The Apache 2.0 license is the correct one. Commercial use is permitted. See https://github.com/chaidiscovery/chai-lab/pull/186
