### ISSUE TITLE
Problems about glyco-protein

### ISSUE THREAD

**Issue by 957-z** [chaidiscovery/chai-lab#201]
Hello~I would like to model a glyco-protein, so could you tell me how to write the input file?

**Comment by wukevin** [comment]
We have support for this landing soon here: https://github.com/chaidiscovery/chai-lab/pull/205

**Comment by arogozhnikov** [comment]
this was merged 🎉 , examples are available in 
https://github.com/chaidiscovery/chai-lab/tree/main/examples/glycosylation
