### ISSUE TITLE
MSA Server error with RNA sequence

### ISSUE THREAD

**Issue by yx0516** [chaidiscovery/chai-lab#206]
Hi,  when i run the prediction with RNA sequence by using MSA server（use_msa_server=True）.  The error happens:

Exception: MMseqs2 API is giving errors. Please confirm your input is a valid protein sequence. If error persists, please try again an hour later.

The input fasta is :

>rna|A
GGGUCUCGCGGAACCGGUGAGUACACCGGAAUCCAGGAAACUGGAUUUGGGCGUGCCCCCGCGAGACC

Can the MSA server skip the RNA or DNA sequence?

**Comment by wukevin** [comment]
I'm not able to reproduce this error; I ran `chai fold --use-msa-server rna_example.fasta outdir` using the following contents of `rna_example.fasta`:

```
>rna|6U8D_1
GGGUCUCGCGGAACCGGUGAGUACACCGGAAUCCAGGAAACUGGAUUUGGGCGUGCCCCCGCGAGACC
>protein|6U8D_2
EISEVQLVESGGGLVQPGGSLRLSCAASGFYISSYSIHWVRQAPGKGLEWVASIYPSYGYTSYADSVKGRFTISADTSKNTAYLQMNSLRAEDTAVYYCARRYRSYYSRYGFDYWGQGTLVTVSSASTKGPSVFPLAPSSKSTSGGTAALGCLVKDYFPEPVTVSWNSGALTSGVHTFPAVLQSSGLYSLSSVVTVPSSSLGTQTYICNVNHKPSNTKVDKKVEPKSCDKTHT
>protein|6U8D_3
SDIQMTQSPSSLSASVGDRVTITCRASQSVSSAVAWYQQKPGKAPKLLIYSASSLYSGVPSRFSGSRSGTDFTLTISSLQPEDFATYYCQQSSYYPSTFGQGTKVEIKRTVAAPSVFIFPPSDEQLKSGTASVVCLLNNFYPREAKVQWKVDNALQSGNSQESVTEQDSKDSTYSLSSTLTLSKADYEKHKVYACEVTHQGLSSPVTKSFNRGEC
```

Perhaps you are missing a the leading carrot `>` in your input so the parsing doesn't happen correctly? The logic is already skipping MSA generation for inputs that are not proteins: https://github.com/chaidiscovery/chai-lab/blob/2d2646bde676da6c9b3fa23b38b47fef8fc0d420/chai_lab/chai1.py#L316-L330

I did realize though, when testing this, that some of the errors we log are overly verbose and do not apply to RNAs; see https://github.com/chaidiscovery/chai-lab/pull/209

**Comment by yx0516** [comment]
@wukevin The above error happens when there is only RNA sequences without proteins.
