### ISSUE TITLE
Covalent Docking

### ISSUE THREAD

**Issue by kanghw0325** [chaidiscovery/chai-lab#207]
Hi, Thanks a lot for this impressive work.

 I can see that 'covalent docking' is not possible to predict using Chai-1. 
Do you guys have any plan to build in Chai-1?

**Comment by wukevin** [comment]
If you are referring to covalently attaching ligands to a residue, we have support for this landing soon here: https://github.com/chaidiscovery/chai-lab/pull/205. Please clarify if you are referring to something else!

**Comment by kanghw0325** [comment]
Thank you so much!
