### ISSUE TITLE
Repeated downloads of model

### ISSUE THREAD

**Issue by LiuSantu123** [chaidiscovery/chai-lab#21]
Each time my colleague and I run a new task, the following files are downloaded in my Conda environment (conda/envs/chailab/lib/python3.11/site-packages/downloads/models): "confidence_head.pt2", "diffusion_module.pt2", "feature_embedding.pt2", "token_input_embedder.pt2", and "trunk.pt2". Additionally, a new directory is created, named with a number (e.g., 256, 512, 1024, etc.). Is there a configuration I can set to prevent this from happening?

**Comment by y1zhou** [comment]
This should be related: https://github.com/chaidiscovery/chai-lab/blob/40dac37389868e19eafa41bb3418c56857a1e79e/chai_lab/chai1.py#L371

The checkpoint used depends on your total number of input tokens, which is wrapped to the closest of 256, 512, etc. and downloaded to corresponding subdirectories.

**Comment by Gibo-Chun** [comment]
> This should be related:
> 
> https://github.com/chaidiscovery/chai-lab/blob/40dac37389868e19eafa41bb3418c56857a1e79e/chai_lab/chai1.py#L371
> 
> The checkpoint used depends on your total number of input tokens, which is wrapped to the closest of 256, 512, etc. and downloaded to corresponding subdirectories.

Thank you for your reply, but I still don't understand how to avoid this problem, and how should I modify the code to avoid this problem.

**Comment by y1zhou** [comment]
I don’t think it’s a problem; they just have different models for different input sequence lengths.

**Comment by arogozhnikov** [comment]
> I don’t think it’s a problem; they just have different models for different input sequence lengths.

@y1zhou is correct, that's expected behavior - different graphs handle different sizes. 

More optimal way to distribute models is in plans.

**Comment by dionjwa** [comment]
I run this on a docker container, with a persisted directory for e.g. caching models. 

Are the models downloaded in a specific directory, and checked, so that if the models are present (already downloaded), they won't be again?

**Comment by arogozhnikov** [comment]
Hi Dion, I've opened a separate issue for this: #51
