### ISSUE TITLE
Prediction of m6A modified RNA

### ISSUE THREAD

**Issue by accibio** [chaidiscovery/chai-lab#22]
Hi! Appreciate the great work.
Is there a way to predict the structure of m6A modified RNA through this tool? I tried the web interface and I can't seem to find a way to incorporate m6A in the FASTA format?

**Comment by wukevin** [comment]
<img width="1817" alt="Screenshot 2024-09-11 at 1 10 07 PM" src="https://github.com/user-attachments/assets/222c90a3-d902-4698-af30-d94d5bd46e2c">

We support m6A modifications (and similar modified bases/residues) by specifying them as a CCD code in `()` in the interface, see the above screenshot for the sequence for [7PO6](https://www.rcsb.org/3d-view/7PO6). Namely, specifying the following two sequences as RNA and Protein entities:
```
GGCGC(6MZ)UCGGCGCC
```
```
GGGGTSKLKYVLQDARFFLIKSNNHENVSLAKAKGVWSTLPVNEKKLNLAFRSARSVILIFSVRESGKFQGFARLSSESHHGGSPIHWVLPAGMSAKMLGGVFKIDWICRRELPFTKSAHLTNPWNEHKPVKIGRDGQEIELECGTQLCLLFPPDESIDLYQVIHKMRH
```
results in the following prediction:
![image](https://github.com/user-attachments/assets/db0ee9e1-cda8-45c4-94b3-addb376dc0c3)


Note however, that this version of Chai-1 isn't trained with DNA/RNA MSAs so may not provide optimal performance for these. Happy folding!
