### ISSUE TITLE
Extra OH group on N linked NAG

### ISSUE THREAD

**Issue by fabgonzal** [chaidiscovery/chai-lab#225]
Thanks for adding glycan support! I noticed an error where N linked glycans starting with NAG retain the OH group off of carbon 1. Which should not be there in the context of N-linked glycosylation.

**Comment by arogozhnikov** [comment]
Hi @fabgonzal, 
can you post small FASTA example for debugging?

**Comment by fabgonzal** [comment]
Sure thing. Below is the fasta and accompanying restraints.
FASTA
\>protein|motif
MGRAMVARLGLGLLLLALLLPTQIYSSETTTGTSSNSSQSTSNSGLAPNPTNATTKAAGGALQSTASLFVVSLSLLHLYS
\>glycan|n_1
NAG(1-4 NAG)
\>glycan|n_2
NAG(1-4 NAG)

RESTRAINTS
restraint_id,chainA,res_idxA,chainB,res_idxB,connection_type,confidence,min_distance_angstrom,max_distance_angstrom,comment
nag1,A,N36@ND2,B,@C1,covalent,1.0,0.0,0.0,toy
nag2,A,N52@ND2,C,@C1,covalent,1.0,0.0,0.0,toy

**Comment by wukevin** [comment]
Thanks for flagging this issue - turns out this was a mixture of (1) a bug in how we were defining glycosidic bonds, and (2) a lack of logic for removing leaving atoms upon bond formation. Both issues have been addressed in the linked PR; let us know if there's anything else that seems off!

**Comment by fabgonzal** [comment]
Great thank you!
