### ISSUE TITLE
Odd results from MAN 3 Branched Glycan

### ISSUE THREAD

**Issue by fabgonzal** [chaidiscovery/chai-lab#227]
Hello, I have had some trouble getting reasonable topologies for branched glycans. For example running with the following fasta and constraints does not produce the correct branching NAG -> NAG -> BMA[branch point]  Am I inputting the glycan incorrectly?
 
FASTA
\>protein|motif
GGGNGSGGG
\>glycan|Man3
NAG(1-4 NAG(1-4 BMA(1-3 MAN)(1-6 MAN)))

CONSTRAINT
restraint_id,chainA,res_idxA,chainB,res_idxB,connection_type,confidence,min_distance_angstrom,max_distance_angstrom,comment
man3,A,N4@ND2,B,@C1,covalent,1.0,0.0,0.0,toy

**Comment by wukevin** [comment]
I reformatted your fasta input as such:

```
>protein|motif
GGGNGSGGG
>glycan|Man3
NAG(4-1 NAG(4-1 BMA(3-1 MAN)(6-1 MAN)))
```

and on this branch https://github.com/chaidiscovery/chai-lab/pull/234, I'm getting the following structure:

![image](https://github.com/user-attachments/assets/b793a532-4031-46d3-8e75-bf29202dda96)

Is this closer to what you are expecting?

**Comment by fabgonzal** [comment]
Looks good! I see now that the specified bonds are from the previous sugar to the subsequent sugar
