### ISSUE TITLE
Pip Package Support for Python 3.10 

### ISSUE THREAD

**Issue by navvye** [chaidiscovery/chai-lab#23]
Noticed that a recent issue added some support for Python 3.10, but I believe this hasn't been extended to the pip package. Running ` !pip install chai_lab ` gives me the following traceback on Colab: 

``` 
ERROR: Ignored the following versions that require a different python version: 0.0.1 Requires-Python >=3.11
ERROR: Could not find a version that satisfies the requirement chai_lab (from versions: none)
ERROR: No matching distribution found for chai_lab
```

**Comment by Jigyashu789** [comment]
It seems more like a python version issue and like for 1st error pip may have find that chai_lab is only compatible with python version - Python 3.11 or the above, you can may well update your version.

**Comment by Garhorne0813** [comment]
you can install a new version:

`pip install git+https://github.com/chaidiscovery/chai-lab.git `

**Comment by arogozhnikov** [comment]
Hi Navvye, please use command posted by @Garhorne0813 for now, we'll publish a version with support of python3.10 on pypi soon.

**Comment by arogozhnikov** [comment]
new version on pypi should support python 3.10:

```
pip install chai_lab==0.1.0
```
