### ISSUE TITLE
Error in loading tokenizer for 'facebook/esm2_t36_3B_UR50D'

### ISSUE THREAD

**Issue by laiyii** [chaidiscovery/chai-lab#241]
I'm running an ordinary task, 
`chai fold input.fasta output_dir`
Here is the error: 
```
OSError: Can't load tokenizer for 'facebook/esm2_t36_3B_UR50D'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same
name. Otherwise, make sure 'facebook/esm2_t36_3B_UR50D' is the correct path to a directory containing all relevant files for a EsmTokenizer tokenizer.
```
There is no local directory with the same name, and [huggingface](https://huggingface.co/models) is accessible.

**Comment by laiyii** [comment]
I have solved this problem by downloading esm2 .bin file manually from [huggingface](https://huggingface.co/facebook/esm2_t36_3B_UR50D/tree/main) and change the parameter file directory ( line 57 in chai_lab/data/dataset/embeddings/esm.py)

**Comment by wtyang908** [comment]
hello，i do it in your way,but it has same probelm,could you please say detail

**Comment by laiyii** [comment]
> hello，i do it in your way,but it has same probelm,could you please say detail

Which files did you copy?

**Comment by wtyang908** [comment]
thanks，I have already solved this .
