### ISSUE TITLE
How dose the seed number influence the results?

### ISSUE THREAD

**Issue by hqdream** [chaidiscovery/chai-lab#246]
Thanks for providing Chai-1 which is remarkable.

I have an question regarding the seed number used in the predict_structure.py script (line 44) in the example directory. Why is this number set to 42? How dose  it influence the results? Will increase the number also increase the prediction performance? If yes, how should I choose a proper seed number (for example when prediction antibody-antigen interaction)?

Thanks a lot!

**Comment by arogozhnikov** [comment]
> Will increase the number also increase the prediction performance?

Nope. Please start from [here](https://vandurajan91.medium.com/random-seeds-and-reproducible-results-in-pytorch-211620301eba) and then ask LLMs further questions.

In short - if you are fine with 5 samples, don't change it.
