### ISSUE TITLE
Were all of AFDB sequences used to generate MSA?

### ISSUE THREAD

**Issue by TheChosenOneJG** [chaidiscovery/chai-lab#252]
I am curious for whether all of AFDB sequences have to generate MSA. Notice that there are more than 290 million monomer sequences in AFDB. Generating all MSA will cost long time if so. Is there any difference if `jackhmmer` and `hhblits` are replaced with `mmseqs/colabfold` ?

**Comment by arogozhnikov** [comment]
> Is there any difference if jackhmmer and hhblits are replaced with mmseqs/colabfold ?

try and see! I'm curious about this question too.

> I am curious for whether all of AFDB sequences have to generate MSA. Notice that there are more than 290 million monomer sequences in AFDB.

that's something to you can ask AF team; there are multiple possible directions to optimize.
