### ISSUE TITLE
chai_lab version 0.5.1 is not available in pip as of 2024.12.20

### ISSUE THREAD

**Issue by resulelgin** [chaidiscovery/chai-lab#255]
Hi, thanks for the great tool!

I tried to install the tool via pip as suggested in README with:
`pip install chai_lab==0.5.1 `

Returns:
```
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement chai_lab==0.5.1 (from versions: 0.0.1, 0.1.0, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.4.1, 0.4.2, 0.5.0)
ERROR: No matching distribution found for chai_lab==0.5.1
```

Then I checked pip website to see whether it is about my pip version. I wasn't able to find the version 0.5.1 in pip. It is only up to 0.5.0. Could you please update the pip version? Thanks a lot!

**Comment by arogozhnikov** [comment]
Hi Resul,

thanks for reporting, it should be fixed now
