### ISSUE TITLE
Regarding inference efficiency

### ISSUE THREAD

**Issue by Kaihui-Cheng** [chaidiscovery/chai-lab#3]
Hi Alex! Amazing work! Well done!
It seems that we're loading the ESM tokenizer and models multiple times during the inference stage for multi-chain processing. Perhaps we could optimize this to improve efficiency.
https://github.com/chaidiscovery/chai-lab/blob/3305f9acada2708fba25bdee3ee35c4abcd0331c/chai_lab/data/dataset/embeddings/esm.py#L62

**Comment by arogozhnikov** [comment]
covered in PR #5 

you can install new version of package:

```bash
pip install git+https://github.com/chaidiscovery/chai-lab.git
```
