### ISSUE TITLE
No such file or directory: '/tmp/outputs/scores.model_idx_2.npz'

### ISSUE THREAD

**Issue by wjk1214** [chaidiscovery/chai-lab#30]
Thank you for providing the tool. When I tried to use it, I received this error message, and I don't know how to resolve it.

Writing output to /tmp/outputs/pred.model_trunk_0_idx_0.pdb
Writing output to /tmp/outputs/pred.model_trunk_0_idx_1.pdb
Writing output to /tmp/outputs/pred.model_trunk_0_idx_2.pdb
Writing output to /tmp/outputs/pred.model_trunk_0_idx_3.pdb
Writing output to /tmp/outputs/pred.model_trunk_0_idx_4.pdb
Traceback (most recent call last):
  File "/chai_lab/examples/predict_structure.py", line 39, in <module>
    scores = np.load(output_dir.joinpath("scores.model_idx_2.npz"))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/anaconda3/envs/chai/lib/python3.12/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/outputs/scores.model_idx_2.npz'

**Comment by duerrsimon** [comment]
Wait for the pip package to update (I ran into the same error just now). 
https://github.com/chaidiscovery/chai-lab/pull/12

**Comment by wjk1214** [comment]
Thank you for your prompt response, it is indeed this reason.

**Comment by wjk1214** [comment]
Thank you for your prompt response, it is indeed this reason.

**Comment by kimdn** [comment]
Unfortunately, I do see this error (`FileNotFoundError: [Errno 2] No such file or directory: '/tmp/outputs/scores.model_idx_2.npz'`).

I did install with latest `pip install chai_lab` as of 9/12/2024 4 PM PST

**Comment by lujessi** [comment]
I also have the latest pip installed, and the tried upgrade pip install chai_lab, but the error still shows: 
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/outputs/scores.model_idx_2.npz'

**Comment by arogozhnikov** [comment]
@lujessi instructions how to install current version are in repo readme.

**Comment by lujessi** [comment]
> @lujessi instructions how to install current version are in repo readme.

Hi arogozhnikov,
Thanks for your reply. I still get a little bit confusion about the solution. You mean we need to wait the update of pip package (the next version), right? The current version of pip is the latest (24.2)

I also tried update chai (since it shows "updates daily"), the problem still exist.

**Comment by arogozhnikov** [comment]
this is from readme:

```
# current version (updates daily):
pip install git+https://github.com/chaidiscovery/chai-lab.git
```

and here is current version of example:

https://github.com/chaidiscovery/chai-lab/blob/main/examples/predict_structure.py

**Comment by lujessi** [comment]
A new error comes out. It indicates the list candidates has no attribute 'cif_path'  .
I just tried the example... 

cif_paths = candidates.cif_paths
                ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'cif_paths'

**Comment by arogozhnikov** [comment]
which indicates that you still didn't install current version.

**Comment by lujessi** [comment]
> which indicates that you still didn't install current version.

Thanks arogozhikov. I got it finally. The reason why I failed is because every time I reinstalled it, but the system seems like cheated and neglected the re-installation. Anyway, it worked. Appreciate for your patience and contribution.
