### ISSUE TITLE
Error running predict_structure.py

### ISSUE THREAD

**Issue by abattenhouse** [chaidiscovery/chai-lab#37]
I just download and pip-installed chai-lab at 2pm Central time today (9/12/2024), and my repo is up to date.

When I run "python predict_structure.py 2>&1 | tee ps.log" it gets an error trying to load the scores file, which was not created. It did produce pdb files; here's the contents of the "outputs" directory I specified:
   example.fasta                            pred.model_trunk_0_idx_2.pdb
   pred.model_trunk_0_idx_0.pdb  pred.model_trunk_0_idx_3.pdb
   pred.model_trunk_0_idx_1.pdb  pred.model_trunk_0_idx_4.pdb

And I've attached my log file. It has warnings but no errors until the np.load. 
[ps.log](https://github.com/user-attachments/files/16985136/ps.log)

Also, the pdb files that were created have 1.00 for all occupancy and temperature factor ATOM values. Finally, no pae or msa files were created. How does one specify that these extra files be created and values be calculated?

Thank you,
Anna Battenhouse
Edward Marcotte lab
The University of Texas at Austin

**Comment by andrewhill157** [comment]
I just ran into this issue as well, but think the discussion in this previous issue is likely relevant https://github.com/chaidiscovery/chai-lab/issues/30

**Comment by arogozhnikov** [comment]
Hi Anna,

> my repo is up to date.

but your code seems to use pip-installed package from pypi; you need to re-install from repo:
```
pip install git+https://github.com/chaidiscovery/chai-lab.git
```
