### ISSUE TITLE
How to get the metrics about predictions?

### ISSUE THREAD

**Issue by GXcells** [chaidiscovery/chai-lab#4]
Hi,

Thanks a lot for open sourcing the model.

Is there a way to output the metrics similar to alpha fold/alphafold multimer and get also coloring of residues based on prediction confidence?

Thanks a lot.

**Comment by arogozhnikov** [comment]
Hi @GXcells 

> get also coloring of residues based on prediction confidence?

I guess that's pLDDT coloring of residues? Sure, we can add this.

> to output the metrics similar to alpha fold/alphafold multimer 

You want to see PDE / PAE matrices or something else?

**Comment by GXcells** [comment]
Yes pLDDT coloring.
For scores, pTM ad ipTM would also be good for multimers.
Also a  PAE plot would be really useful.

Thanks a lot.

**Comment by arogozhnikov** [comment]
pLDDT coloring was just merged in #8 , not yet exposed in web server

**Comment by jacquesboitreaud** [comment]
@GXcells we now write a scores file alongside the pdbs ( #12), you can get ptm and iptm as follows: 

```python
# Load pTM, ipTM, pLDDTs and clash scores for sample 2
scores = np.load(output_dir.joinpath("scores.model_idx_2.npz"))

ptm = scores["ptm"]
iptm = scores["iptm"]

all_available_scores = list(scores.keys())
```
the scores also contain per-chain pTM and per-chain-pair ipTM if you need more detailed metrics.

**Comment by GXcells** [comment]
Great Thank you all. I close the issue.
