### ISSUE TITLE
The prediction results of Chai-1 protein-ligand were significantly different from those of RoseTTA-Fold-All-Atom

### ISSUE THREAD

**Issue by biochristmas** [chaidiscovery/chai-lab#42]
![image](https://github.com/user-attachments/assets/6eaebdd2-c690-426c-9a50-3a15919b94ae)
output of Chai-1
![image](https://github.com/user-attachments/assets/a9c10788-ea51-40c7-b011-908c9ad1716b)
output alignment
![image](https://github.com/user-attachments/assets/122031c5-3c22-44a5-8c13-59f8d0b09a3c)
output of RFAA

Hi, in order to test the Chai-1, I used the protein-ligand example of RoseTTAFold-All-Atom for testing, but the result seemed to be quite different from the predicted result of RoseTTAFold-All-Atom, and the RMSD of the comparison of the two structures was 21.452 angstroms. Is this a normal situation? The following is the content of the fasta file I predict to use:
>protein|7QXR_1
TATGDEWWAKCKQVDVLDSEMSYYDSDPGKHKNTVIFLHGNPTSSYLWRNVIPHVEPLARCLAPDLIGMGKSGKLPNHSYRFVDHYRYLSAWFDSVNLPEKVTIVCHDWGSGLGFHWCNEHRDRVKGIVHMESVVDVIESWDEWPDIEEDIALIKSEAGEEMVLKKNFFIERLLPSSIMRKLSEEEMDAYREPFVEPGESRRPTLTWPREIPIKGDGPEDVIEIVKSYNKWLSTSKDIPKLFINADPGFFSNAIKKVTKNWPNQKTVTVKGLHFLQEDSPEEIGEAIADFLNELT
>ligand|NSW
c1c(ccc(Cn2[nH]c3c(Cc4ccccc4)nc(c4ccc(cc4)O)c[n+]3c2=O)c1)O

**Comment by biochristmas** [comment]
aggregate_score:
[0.15987574]

ptm:
[0.27837044]

iptm:
[0.13025206]

per_chain_ptm:
[[0.27259728, 0.7072335 ]]

per_chain_pair_iptm:
[[[0.27259728, 0.03284407],
  [0.13025206, 0.7072335 ]]]

has_clashes:
[0.]

per_chain_intra_clashes:
[[0., 0.]]

per_chain_pair_inter_clashes:
[[[0., 0.],
  [0., 0.]]]

This is the score information of the predicted result, it seems that ipTM is very low, is it because I manually updated several scripts that have been updated in the github repository recently?

**Comment by kimdn** [comment]
Is Chai-1 more accurate than RFAA ?
https://www.chaidiscovery.com/blog/introducing-chai-1

**Comment by navvye** [comment]
Interesting. Do you have a ground truth so that you can compare the two predictions?

**Comment by biochristmas** [comment]
I performed a comparison, and the results show that the structure provided by RFAA is closer to the experimental structure in the PDB. This discrepancy might be due to my not using MSA information during the Chai-1 run. I am currently exploring how to incorporate MSA information and would greatly appreciate any suggestions you could offer.

**Comment by arogozhnikov** [comment]
@biochristmas we'll add some examples how to pass MSAs, but the simplest way right now is to use web server - search for MSAs is automated there.

Here is your example vs PDB:

![screenshot_2024-09-12_at_9 55 11___pm_720](https://github.com/user-attachments/assets/c1f83538-8ca0-4352-9431-90b063f33319)

**Comment by arogozhnikov** [comment]
also @biochristmas from you description it isn't clear how many samples your generated and how you selected best sample (that's what server does by default, but in code we return all samples)

**Comment by biochristmas** [comment]
Thank you very much for your prompt response. After modifying the input and output paths in example/predict_structure.py, I ran predictions on the case mentioned earlier and generated a total of 5 samples. However, the ipTM scores in the resulting npz files appear to be quite low. I am very much looking forward to the example on how to pass the MSA.

**Comment by biochristmas** [comment]
![image](https://github.com/user-attachments/assets/5fdddfd5-1018-4d36-a476-7eafdc3ab4f4)
[scores.model_idx_0.txt](https://github.com/user-attachments/files/17000467/scores.model_idx_0.txt)
[scores.model_idx_1.txt](https://github.com/user-attachments/files/17000468/scores.model_idx_1.txt)
[scores.model_idx_2.txt](https://github.com/user-attachments/files/17000469/scores.model_idx_2.txt)
[scores.model_idx_3.txt](https://github.com/user-attachments/files/17000470/scores.model_idx_3.txt)
[scores.model_idx_4.txt](https://github.com/user-attachments/files/17000471/scores.model_idx_4.txt)

**Comment by biochristmas** [comment]
[output_pdb.zip](https://github.com/user-attachments/files/17000484/output_pdb.zip)
This is the PDB file for the five output results I obtained from the run.

**Comment by GXcells** [comment]
> arogozhnikov

Was there MSA here ? Is it ON by default on the web server? Would be interesting to see with/without MSA on web server to compare to @biochristmas local results

**Comment by YangPH0624** [comment]
> also @biochristmas from you description it isn't clear how many samples your generated and how you selected best sample (that's what server does by default, but in code we return all samples)

You have done an amazing job, but the server has recently not supported MSA. When will it be possible to perform MSA locally?

**Comment by arogozhnikov** [comment]
Closing, MSA/MSAContext discussion should goes in #73, and track corresponding PR in #109
