### ISSUE TITLE
save the results in both .pdb and .cif formats

### ISSUE THREAD

**Issue by Garhorne0813** [chaidiscovery/chai-lab#49]
Hello! I have pulled the latest repository and noticed that currently chai-1 only saves results in the .cif format. For better usability, could we save the results in both .pdb and .cif formats, similar to AlphaFold2?

Thank you!

**Comment by navvye** [comment]
You can convert .cif to .pdb pretty easily using Biopython. I'm attaching a link.
https://gist.github.com/sbliven/b7cc2c5305aa3652a75a580ae7c6ce33

Shouldn't take you more than 5 lines of modifications to get this up & running for the directory in which you have set up your .cif files!

**Comment by aozalevsky** [comment]
I can also recommend using [Biotite](https://www.biotite-python.org/latest/), [GEMMI](https://gemmi.readthedocs.io/en/latest/), and [ProDy](https://github.com/prody/ProDy) for working with `PDBx/mmCIF` files, as well as [python-modelcif](https://github.com/ihmwg/python-modelcif) a reference implementation of the ModelCIF extension, that gives a lower-level access to the content. 

As I mentioned [here](https://github.com/chaidiscovery/chai-lab/commit/bc5486ec92952c310d7e17d7afc2cf14b54d83e6#commitcomment-146517755) PDB is an outdated format, and PDBx/mmCIF is a modern standard (including ModelCIF extensions for computed models), which is already widely adopted by the community. AF3 server, for instance, also generates only CIF-formatted models.

I totally understand that updating established in-house pipelines is hard, but if we as a community don't adopt and improve new standards and tools, we will never get to the point where they're comfortable as good ol' PDB.
