### ISSUE TITLE
Differences between the GitHub Open Version and the Page Server Version

### ISSUE THREAD

**Issue by gibhdyw** [chaidiscovery/chai-lab#50]
I would like to ask about the differences between the version you have open on GitHub and the current server version on your page. I noticed that the page seems to be using MSA, while the GitHub version deployed locally uses the ESM model weights.

**Comment by arogozhnikov** [comment]
Hi duyouwei, 

yes, server additionally collects MSAs for user and selects the best result by score.

**Comment by gibhdyw** [comment]
Can I also use MSA after local deployment? Since I find that the results are different on the local deployment and on the server page, obviously the effect on the server looks more reliable, could there be a section on readme on how to add the msa search function on the local deploy。

**Comment by arogozhnikov** [comment]
yes, that's in plans
