### ISSUE TITLE
How do I control where downloaded weights are saved?

### ISSUE THREAD

**Issue by arogozhnikov** [chaidiscovery/chai-lab#51]
Currently we store model weights in two places (one is <pkg_root>/downloads, second esm location defined by huggingface). 

It would be nice to provide some envvar (or some other mean) so that users could explicitly set where the model is saved.

Motivating example was provided by @dionjwa in #21 where weights are re-downloaded in docker container on every container restart.

It could also help with cases like #29

**Comment by dionjwa** [comment]
👍 Being able to set an env var where the models are saved would be the best solution for me

**Comment by arogozhnikov** [comment]
Hey @dionjwa I've just merged #61, so you could control path with envvar `CHAI_DOWNLOADS_DIR`

**Comment by arogozhnikov** [comment]
Documented CHAI_DOWNLOADS_DIR in repo readme, closing

**Comment by dionjwa** [comment]
Thank you!
