### ISSUE TITLE
Phosphorylated residues have an additional oxygen

### ISSUE THREAD

**Issue by magnusbauer** [chaidiscovery/chai-lab#56]
When adding phosphorylations to a sequence, in this case a phosphotyrosine like that "AAA(PTR)AAA" the backbone gets an additional oxygen. Its maybe because the CCD ligand summary is a C-terminal phosphotyrosine but only one oxygen is needed in this case when its part of a peptide chain.

<img width="720" alt="image" src="https://github.com/user-attachments/assets/ac5abf67-a377-4d30-94ea-1f3a7d9bf8a0">

**Comment by arogozhnikov** [comment]
Hi Magnus, thanks for reporting!

> in this case a phosphotyrosine

is this problem specific for phosphotyrosine or you observe this for all kinds of phosphorylations?

**Comment by magnusbauer** [comment]
I also got it for phosphoserines, phosphothreonines and acetyllysines. I guess its the case for all PTMs that are a full residue including backbone in the CCD since they all have two oxygens as would be found on the C-terminus and not in a continuous peptide chain. These were examples where I encountered them: PTR (as above), SEP, TPO and ALY (below). So not only phosphorylations but luckily it seems like it does not affect the overall prediction a lot from what I see. For glycosylations (like NAG) I'm not sure since they can't be properly included yet using that notation I think

<img width="783" alt="image" src="https://github.com/user-attachments/assets/8ba3b217-9d39-4f19-8b74-8828a245527c">

**Comment by arogozhnikov** [comment]
thank you for checking!

> glycosylations ... can't be properly included yet using that notation I think

That's correct. Maybe you have recommendations how should we take this input from user?

**Comment by arogozhnikov** [comment]
Hey Magnus, this was fixed in #62. Thanks again!

**Comment by magnusbauer** [comment]
> Maybe you have recommendations how should we take this input from user?

Very cool! Thanks so much for taking care of it so quickly! It works like a charm now. For including glycosylation a possibility would be to also use a bracket connotation that connects them to the previous residue. That may become difficult though if connections are not clear or people want specific non-standard connections like disulfide bonds. I think there only providing the option for manually setting connections would help.

**Comment by GXcells** [comment]
How do you know code in FASTA for non standard residues?
Could not find any info online or in the technical report of chai lab

**Comment by vreis** [comment]
@GXcells: this is undocumented right now but we do support the following CCD codes for modified residues: https://gist.github.com/vreis/ade09df89900310da79f3fc5e2ecac28

You specify a modified residue as a CCD code in parenthesis in the aminoacid sequence, something like `GVSGH(LLP)MIGS`

**Comment by GXcells** [comment]
Thanks a lot ;(

**Comment by magnusbauer** [comment]
> That may become difficult though if connections are not clear

Just be aware only because it is available in the CCD it might not be connected properly as for NAG for example, see below. That was our discussion before. I think right now it only works if its included as a full residue including backbone

<img width="922" alt="image" src="https://github.com/user-attachments/assets/4fdae659-02a9-4ac2-9f5d-c0c7f5d2fff4">

**Comment by arogozhnikov** [comment]
> I think right now it only works if its included as a full residue including backbone

that's correct. I guess we'll need to deal with this case-by-case unless someone already did a job of mapping to some 'canonical' state.
