### ISSUE TITLE
chai_lab.chai1.UnsupportedInputError: Too many tokens in input: 4775 > 2048. 

### ISSUE THREAD

**Issue by chengwbTOT** [chaidiscovery/chai-lab#58]
When I enter my  sequence on my  server, the following error is reported :
"chai_lab.chai1.UnsupportedInputError: Too many tokens in input: 4775 > 2048. Please limit the length of the input sequence."
Is there any way to solve this problem?

All the best！
Wenbin cheng

**Comment by arogozhnikov** [comment]
hi @chengwbTOT 

Example of counting tokens - each canonical AA is one token; for ligands and non-canonical AAs every atom is a token.

models allow inference on up to 2048 tokens, that's what reported, and recommendation is also there:

> Please limit the length of the input sequence.
