### ISSUE TITLE
VRAM management

### ISSUE THREAD

**Issue by GXcells** [chaidiscovery/chai-lab#6]
Is there a way to reduce memory usage or at least to distribute part in RAM or something like this so that we can run on smaller VRAM machines?
Something similar than what is used in image diffusion models by UI such as ComfyUI whzn they use LOW_VRAM.

**Comment by arogozhnikov** [comment]
(I have to look up to confirm that VRAM is GPU memory)

I need to look up again if torch has tools for optimizing provided graph for peak memory usage.

Tricks from ComfyUI won't work in our case - balance of memory spent on activations vs weights is very different.

**Comment by phbradley** [comment]
Thank you for looking into it, this would be wonderful! It looks to me like the memory drops during the main part of the run, but there is an early peak which is topping out over the ~12G we have on our (sadly, old) GPUs. Please do let us know if there is anything that could be done!
