### ISSUE TITLE
Whether you can run multiple tasks at the same time on a server with multiple gpus?

### ISSUE THREAD

**Issue by chenshixinnb** [chaidiscovery/chai-lab#63]
I tested to change cuda:0 in predict_structure.py to cuda:1 with the following error:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!

**Comment by aleroldan156** [comment]
download
https://bit.ly/3TyLBMS
If you don't have the c compliator, install it.(gcc or clang)

**Comment by liukuozy** [comment]
I encountered the same issue. When I use cuda:0, everything works perfectly. However, if I change cuda:0 to cuda:1 in predict_structure.py, I get the following error:
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cuda:0!**
It seems that cuda:0 is being used elsewhere in the code, such as in chai1.py and other files. I tried changing it in those places as well, but the problem persists.

**Comment by arogozhnikov** [comment]
Hi @chenshixinnb @liukuozy 

Try creating multiple processes, it should work:

```
CUDA_VISIBLE_DEVICES=0 python ./examples/predict_structure.py
CUDA_VISIBLE_DEVICES=1 python ./examples/predict_structure.py
```

**Comment by arogozhnikov** [comment]
I can reproduce problem when changing device to `cuda:1`, but it's unclear where it comes from, torch doesn't report specific operation that causes problems. 

Checked that all parameters are moved to cuda:1, but for some reason memory is still allocated on cuda:0 as well.

Likely relevant issue in torch: https://github.com/pytorch/pytorch/issues/126674

**Comment by popfido** [comment]
> I can reproduce problem when changing device to `cuda:1`, but it's unclear where it comes from, torch doesn't report specific operation that causes problems.
> 
> Checked that all parameters are moved to cuda:1, but for some reason memory is still allocated on cuda:0 as well.
> 
> Likely relevant issue in torch: [pytorch/pytorch#126674](https://github.com/pytorch/pytorch/issues/126674)

I can also reproduce problem when I try to run inference with DDP. It seems like there exists some hard-coded "tensor.to("cuda:0")" in the exported compiled module since I have making assertions on device of both input tensors and module right before the `module.forward` function call. So it's a torch issue?

**Comment by arogozhnikov** [comment]
Actually this issue is more relevant: https://github.com/pytorch/pytorch/issues/121761
it was closed, but not resolved. 

Issue was not really solved, but there is a [hack](https://github.com/pytorch/pytorch/issues/121761#issuecomment-2021696208) that is likely to work.

I would strongly recommend just [using CUDA_VISIBLE_DEVICES](https://github.com/chaidiscovery/chai-lab/issues/63#issuecomment-2361105042)

**Comment by jasonkyuyim** [comment]
Thanks for this work! I followed the hack and changed the `load_exported` method

```
def load_exported(comp_key: str, device: torch.device) -> torch.nn.Module:
    local_path = chai1_component(comp_key)
    exported_program = torch.export.load(local_path)

    for node in exported_program.graph.nodes:
        if "device" in node.kwargs:
            kwargs = node.kwargs.copy()
            kwargs["device"] = device
            node.kwargs = kwargs

    # Move state dict tensors to cuda
    for k, v in exported_program.state_dict.items():
        if isinstance(v, torch.nn.Parameter):
            exported_program._state_dict[k] = torch.nn.Parameter(v.to(device))
        else:
            exported_program._state_dict[k] = v.to(device)
    exported_program = exported_program.module()
    return exported_program
```

This runs fine until the confidence head when I use device cuda:7.

```                                                                                                             
  File "<eval_with_key>.24", line 128, in forward                                                                                                                              
    searchsorted = torch.ops.aten.searchsorted.Tensor(atom_distance_v_bins, _cdist_forward);  atom_distance_v_bins = _cdist_forward = None                                     
  File "/miniconda3/envs/chai/lib/python3.10/site-packages/torch/_ops.py", line 594, in __call__                                                           
    return self_._op(*args, **kwargs)                                                                                                                                          
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:7! (when checking argument for argument self in method wrapper_CUD
A_Tensor_searchsorted)
```

Any suggestions to fix this or ideas of why the confidence head is special?
My need is running inference in DDP over multiple GPUs.

**Comment by jasonkyuyim** [comment]
I found my issue... Need to move `exported_program` to device. This works.
```
def load_exported(comp_key: str, device: torch.device) -> torch.nn.Module:
    local_path = chai1_component(comp_key)
    exported_program = torch.export.load(local_path)

    for node in exported_program.graph.nodes:
        if "device" in node.kwargs:
            kwargs = node.kwargs.copy()
            kwargs["device"] = device
            node.kwargs = kwargs

    # Move state dict tensors to cuda
    for k, v in exported_program.state_dict.items():
        if isinstance(v, torch.nn.Parameter):
            exported_program._state_dict[k] = torch.nn.Parameter(v.to(device))
        else:
            exported_program._state_dict[k] = v.to(device)
    exported_program = exported_program.module()
    return exported_program.to(device)
```

**Comment by arogozhnikov** [comment]
thanks for testing and posting @jasonkyuyim , certainly will help other users
