### ISSUE TITLE
Query about adding pocket and contact constraints in chi-1

### ISSUE THREAD

**Issue by tianflame** [chaidiscovery/chai-lab#65]
Dear chi-1 Development Team,

I am a researcher who is very interested in chi-1. I recently read the technical report for chi-1 and I'm particularly intrigued by the use of **pocket constraints and contact constraints** in antigen-antibody complex structure prediction, as shown in Figure 4.

I would like to inquire about how to add these constraints in the input for general protein-protein complex structure prediction. Could you provide a specific example demonstrating how to specify these constraints in the input file?

Your assistance would be greatly appreciated.

**Comment by arogozhnikov** [comment]
Hi @tianflame 

See #27 , we will add more user-friendly interface for contact constraints soon
