### ISSUE TITLE
 Chai-lab Web Server predicts Intermolecular Forces?

### ISSUE THREAD

**Issue by Jason-Han-Hu** [chaidiscovery/chai-lab#66]
I noticed that the Chai-lab web server can directly display **intermolecular forces** between complexes. Are these forces predicted by Chai-lab based on amino acids capable of forming salt bridges, hydrogen bonds, and the distances between them? Is it possible to visualize these interactions in PyMOL?

![image](https://github.com/user-attachments/assets/2f45f2d7-ff6e-4687-8317-03d410f55d24)

**Comment by joshim5** [comment]
These are provided by the visualization engine, not directly predicted by Chai-1. In other words, if Chai-1 predicts certain atoms to be within certain distances, an IMF will be shown.
