### ISSUE TITLE
How to disable MSA?

### ISSUE THREAD

**Issue by andrew0901** [chaidiscovery/chai-lab#79]
Hi,

This is a great model and I'm excited to work with it. I wish to run it on some computing cluster nodes without internet access so I'd like to run in single-sequence mode without MSA (it seems to me that your code is accessing a remote database for MSA, correct me if I'm wrong). I'm wondering if there is a flag somewhere to disable MSA sampling? Appreciate your help!

**Comment by arogozhnikov** [comment]
Hi @andrew0901, model does not pull MSA from internet, it relies on ESM embeddings instead.

When you start the model, model auto-downloads necessary weights for itself (for several sizes) and for the ESM. By default everything is stored in <package root>/downloads, but can be changed with envvar, see #51 for details.
