### ISSUE TITLE
CPU version for structure inference?

### ISSUE THREAD

**Issue by tommyhuangthu** [chaidiscovery/chai-lab#85]
Dear team, 

We have few protein targets that are longer than 1000 AAs. These targets caused the out-of-memory issues on both A100 40GB and A40 48GB GPUs in the University's cluster. The cluster does not have A100 80GB GPUs. Could your team provide a version that can use CPUs for structure inference?

Thanks,
Tommy

**Comment by arogozhnikov** [comment]
Hi Tommy, 

there is already discussion #19 about CPU. 
TLDR: that's not a priority for now. Compute time scales as N^3, so for big complexes you really want GPU. 

Also see #69 , maybe some option will work for you
