### ISSUE TITLE
Model python source code

### ISSUE THREAD

**Issue by hadim** [chaidiscovery/chai-lab#89]
Where can we access the Python source code of the different modules of the model? Unless I missed it, it seems that currently the modules are directly loaded from pickle files.

**Comment by arogozhnikov** [comment]
Hey hadrien, 

files aren't pickles, those are exported torch graphs, so you don't need any python code to run inference. You can read about this [in torch documentation](https://pytorch.org/docs/stable/export.html)

**Comment by hadim** [comment]
Thank you for your answer.

Indeed, those are exported graphs, but my original question is about being able to access to original Python code of the different modules. Would that be possible to provide it? 

It should be possible to reverse engineer it from the exported graphs, but it would be a bit time-consuming!

**Comment by arogozhnikov** [comment]
> Would that be possible to provide it?

no promises, certainly not a priority

**Comment by sokrypton** [comment]
> > Would that be possible to provide it?
> 
> no promises, certainly not a priority

This should be the highest priority of the project.
