### ISSUE TITLE
large  SMILES input

### ISSUE THREAD

**Issue by yamskop2** [chaidiscovery/chai-lab#93]
Thank you for this interesting model. I was generating the models of oligosaccharide (composed of 12 repeating monosaccharides, as a ligand) and three protein subunits.  I got the following error _".../lib/python3.10/site-packages/chai_lab/data/sources/rdkit.py", line 98, in _load_ref_conformer_from_rdkit    ref_pos = torch.tensor(mol.GetConformer().GetPositions(), dtype=torch.float)
ValueError: Bad Conformer Id...."._ Only protein complex  models without the oligosaccharide ligand were generated. 

However, when I shorten the oligosaccharide to four monosaccharides and input the corresponding SMILES string, the protein complexes with the tetrasaccharide were generated successfully. Could this mean that RDKit struggles with complex SMILES for larger oligosaccharides? Should I avoid treating large oligosaccharides as ligands? Thank you.

**Comment by arogozhnikov** [comment]
> Should I avoid treating large oligosaccharides as ligands? 

ligands is the right way to input oligosaccharides (at least, for now)

> Could this mean that RDKit struggles with complex SMILES for larger oligosaccharides? 

apparently. Error comes from RDKit, not from out code.

I suggest just trying to generate reference conformer with plain RDkit, and confirm if it fails. This fragment should help you get started:

https://github.com/chaidiscovery/chai-lab/blob/306f53c7f45a6dd082aabd0d82a36d64fcf51f82/chai_lab/data/sources/rdkit.py#L144-L161

**Comment by yamskop2** [comment]
> > Should I avoid treating large oligosaccharides as ligands?
> 
> ligands is the right way to input oligosaccharides (at least, right now)
> 
> > Could this mean that RDKit struggles with complex SMILES for larger oligosaccharides?
> 
> apparently. Error comes from RDKit, not from out code.
> 
> I suggest just trying to generate reference conformer with plain RDkit, and confirm if it fails. This fragment should help you get started:
> 
> https://github.com/chaidiscovery/chai-lab/blob/306f53c7f45a6dd082aabd0d82a36d64fcf51f82/chai_lab/data/sources/rdkit.py#L144-L161

Hi Arogozhnikov, I appreciate your prompt reply. As you suggested, I have confirmed the reason for the 'Bad Conformer Id' error with RDKit. RDKit successfully generates conformers for my tetrasaccharide but reports an error after a long run for the hexasaccharide. The modeling results for the tetrasaccharide and proteins make a lot of sense, and it would be great if larger oligosaccharides could be input. Do you have any further suggestions for resolving this RDKit 'Bad Conformer Id' issue, or would chai-lab accept ligand conformers generated by other software.  Thank you for your help.

**Comment by yamskop2** [comment]
Hi Arogozhnikov,

I appreciate your prompt reply. As you suggested, I have confirmed the reason for the 'Bad Conformer Id' error with RDKit. RDKit successfully generates conformers for my tetrasaccharide but reports an error after a long run for my hexasaccharide. The modeling results for the tetrasaccharide and proteins make a lot of sense, and it would be great if larger oligosaccharides could be input.

Do you have any further suggestions for resolving this RDKit 'Bad Conformer Id' issue? Would Chai accept ligand conformers generated by other software?

Thank you for your help.
